import { createRequire } from 'node:module';
import { copyFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
const require = createRequire(import.meta.url);
const out = 'generated';
mkdirSync(out,{recursive:true});
const ortDist = dirname(require.resolve('onnxruntime-web'));
for (const f of ['ort-wasm-simd-threaded.mjs','ort-wasm-simd-threaded.wasm']) copyFileSync(join(ortDist,f),join(out,f));
const fenshotEntry = require.resolve('@scoriiu/fenshot');
const pkgRoot = join(dirname(fenshotEntry),'..');
copyFileSync(join(pkgRoot,'model','chess-tiles-v2.onnx'),join(out,'chess-tiles-v2.onnx'));
console.log('Fenshot model and ONNX runtime prepared.');